# 服务名称
spring:
  application:
    name: micr-dataservice
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zfb2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: huhang0113

# 设置mybatis
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# dubbo基本配置
#dubbo:
#  registry:
#    accepts: zookeeper://127.0.0.1:2181
#  scan:
#    base-packages: com.hh.dataservice.service
#  provider:
#    timeout: 100000
#    retries: 0

dubbo:
  metadata-report:
    address: zookeeper://127.0.0.1:2181?timeout=600000
  config-center:
    address: zookeeper://127.0.0.1:2181?timeout=600000
  application:
    name: user-dubbo
  registry:
    address: zookeeper://127.0.0.1:2181?timeout=600000
    client: curator
  scan:
    base-packages: com.hh.dataservice.service
  protocol:
    threadpool: cached
    name: dubbo
    port: 8739
  provider:
    threads: 100

# 密码的盐
zfb:
  config:
    password-salt: nq80rh80hne8h2jd9qhejqeqwu8eh8uq




